Update sendinblue link
strapi/awesome-strapi pull request #37
Opened 2021-02-25 13:48 UTC by yanotoma

#### By submitting this pull request, I promise that:

- [ ] I have read the [contribution guidelines](https://github.com/strapi/awesome-strapi/blob/master/CONTRIBUTING.md) thoroughly.
- [ ] I ensure my submission follows each and every point.

2021-02-26 11:53 UTC, Lith commented
Hi,

I think it will be better to let the old version, I'm using the version of @eddybordi since 2 years now... and yes, he's not maintain the repository, and yes, it's a bit annoying to have my PR in review since many month (https://github.com/eddybordi/strapi-provider-email-sendinblue/pull/5/files) 

I suggest to add your version, but keep the oldest ?

Thanks !

2021-02-26 19:26 UTC, derrickmehaffy requested changes

2021-02-26 19:26 UTC, derrickmehaffy commented on README.md
> +- [Sendinblue](https://github.com/yanotoma/strapi-provider-email-sendinblue) - Sendinblue email provider.
I concur with @Lith, can you please modify this to state the previous package as outdated and add yours below it as a new version?

2021-02-27 23:44 UTC, Lith commented
I've send a message to eddybordi, and he will give me right to npmjs repos, so I will be able to maintain it and keep it up to date.
So... I'm not sure this new package will be interesting here (too confused?). Just wait a few days :) 

Otherwise @yanotoma, we really appreciate your work, the main object here is to avoid confusion with 2 same packages.
It's better to have once with many collaborators, instead of many with one collaborator.

2021-03-01 21:55 UTC, derrickmehaffy commented
> I've send a message to eddybordi, and he will give me right to npmjs repos, so I will be able to maintain it and keep it up to date.
> So... I'm not sure this new package will be interesting here (too confused?). Just wait a few days :)
> 
> Otherwise @yanotoma, we really appreciate your work, the main object here is to avoid confusion with 2 same packages.
> It's better to have once with many collaborators, instead of many with one collaborator.

Thank you very much @Lith I agree it would be better to have a single source of truth with multiple contributors. For the moment I'll place this PR on hold until we have a confirmed answer as to the lead maintainer for the package.

2021-03-04 21:39 UTC, yanotoma commented
Hi guys, sorry for not answer 
I agree to have only one repo for this, so I think the current repo can stay if you can update it I have no problem with that
You can check my repo or let me know if I can help with something

2021-03-29 17:38 UTC, derrickmehaffy commented
@Lith did you hear back from eddybordi ?

2021-06-30 15:15 UTC, derrickmehaffy commented
Going to close this as we haven't heard any information yet. We can reopen once we have some more updated information.

2021-06-30 15:15 UTC, closed without merging